version: '3.8'

networks:
  ecommerce-vpc:
    driver: bridge

services:
  mysql-service:
    image: mysql:latest
    restart: always
    ports:
      - '3309:3306'
    expose:
      - '3306'
    volumes:
      - .docker/ecommerce-mysql:/var/lib/mysql
    networks:
      - ecommerce-vpc
    env_file:
      - ./services/.env

  ecommerce-nginx-service:
    image: ecommerce/ecommerce-nginx-service
    container_name: ecommerce-nginx-container
    build:
      args:
        user: app_user
        uid: 1000
      context: .
      dockerfile: services/nginx/Dockerfile
    restart: always
    tty: true
    ports:
      - 8000:80
    volumes:
      - ./backend/:/var/www
      - ./services/nginx/conf:/etc/nginx/conf.d
    networks:
      - ecommerce-vpc
    env_file:
      - ./services/.env

  ecommerce-application-service:
    image: ecommerce/ecommerce-application-service
    container_name: ecommerce-application-container
    build:
      args:
        user: app_user
        uid: 1000
      context: .
      dockerfile: services/api/Dockerfile
    depends_on:
      - mysql-service
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - ./backend/:/var/www
    networks:
      - ecommerce-vpc
    env_file:
      - ./services/.env
