version: '3.8'

networks:
  ecommerce-vpc:
    driver: bridge

services:
  mysql-service:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'ecommerce'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root123'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3309:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - .docker/my-db:/var/lib/mysql
    networks:
      - ecommerce-vpc

  application-service:
    image: ramesrest/ecommerce-service
    container_name: application-service-container
    depends_on:
      - mysql-service
    networks:
      - ecommerce-vpc
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    restart: unless-stopped
